name: Test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: touch .env.production && echo "VITE_API_KEY=${{ secrets.FIREBASE_DEV_API_KEY }}\nVITE_AUTH_DOMAIN=${{ secrets.FIREBASE_DEV_AUTH_DOMAIN }}\nVITE_DATABASE_URL=${{ secrets.FIREBASE_DEV_DATABASE_URL }}\nVITE_PROJECT_ID=${{ secrets.FIREBASE_DEV_PROJECT_ID }}\nVITE_STORAGE_BUCKET=${{ secrets.FIREBASE_DEV_STORAGE_BUCKET }}\nVITE_MESSAGING_SENDER=${{ secrets.FIREBASE_DEV_MESSAGING_SENDER }}\nVITE_APP_ID=${{ secrets.FIREBASE_DEV_APP_ID }}" > .env.production
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: ".env.production"

      - name: File contents
        run: echo "${ steps.read_file.outputs.contents }"
